### ISSUE TITLE
Can't import radio from Firebase

### ISSUE THREAD

**Issue by oskarrough** [radio4000/cms#49]
It says success but...

![image](https://user-images.githubusercontent.com/184567/151873846-e79d9f28-da5c-4856-b76a-be9c4c6a3a41.png)

there's an error

![image](https://user-images.githubusercontent.com/184567/151873779-294ca499-112c-47ac-8e76-a272aad68d1d.png)

**Comment by oskarrough** [comment]
Works locally though. The API at https://api.radio4000.com/api/import/firebase-realtime  throws `500`:

```
[POST] /api/import/firebase-realtime
14:30:15:34
running
Error migrating Error: Called end on pool more than once
    at BoundPool.end (/var/task/node_modules/pg-pool/index.js:399:19)
    at migrate (/var/task/.next/server/chunks/648.js:79:107)
```

**Comment by oskarrough** [comment]
Switched beta.radio4000.com to use the second "beta" Supabase instance. It's already set up to use Firebase prod, as the api.radio4000.com, as far as I can tell.

Still, now I'm getting `Invalid token: signature is invalid', status: 401` from the firebase-realtime endpoint. Not sure which key is wrong..

**Comment by oskarrough** [comment]
Worked for me a couple of days ago
